id: P5D55E3DF
initial_creation_type: input
source_metadata:
  title: 'Nāgārjuna: Mūlamadhyamakakārikā'
  language: sa
  volumes:
    e5845b47b0ab44ad96632300fc2094f1:
      title: 'CIII_Chapter XI: Pūrvāparakoṭiparīkṣa'
      base_file: 'CIII_Chapter XI: Pūrvāparakoṭiparīkṣa.txt'
      work_id: WFF47416C
    b20abe9090f9413090fc51527447bb68:
      title: 'CIII_Chapter XII: Duḥkhaparīkṣā'
      base_file: 'CIII_Chapter XII: Duḥkhaparīkṣā.txt'
      work_id: W04D3636E
    646d574080bc467c94a1889425e6215b:
      title: 'CIII_Chapter XIII: Saṃskāraparīkṣā'
      base_file: 'CIII_Chapter XIII: Saṃskāraparīkṣā.txt'
      work_id: WE76926C6
    06f968eeaf3a47b297212d6a44988111:
      title: 'CIII_Chapter XIV: Saṃsargaparīkṣā'
      base_file: 'CIII_Chapter XIV: Saṃsargaparīkṣā.txt'
      work_id: W15139221
    8566345b380143a4be7a8a6dfc789bd4:
      title: 'CIII_Chapter XV: Svabhāvaparīkṣā'
      base_file: 'CIII_Chapter XV: Svabhāvaparīkṣā.txt'
      work_id: W8C979E1D
    e67fcb3808464567a5b4eb53ac576cc5:
      title: 'CII_Chapter IX: Pūrvaparīkṣā'
      base_file: 'CII_Chapter IX: Pūrvaparīkṣā.txt'
      work_id: WE39A7D69
    8e99d8966fda4596838e297dc92cbb32:
      title: 'CII_Chapter VI: Rāgasaktiparīkṣā'
      base_file: 'CII_Chapter VI: Rāgasaktiparīkṣā.txt'
      work_id: W93C092C9
    e923be81327f48a3bc54c19920767c56:
      title: 'CII_Chapter VII: Saṃskr̥̥taparīkṣā'
      base_file: 'CII_Chapter VII: Saṃskr̥̥taparīkṣā.txt'
      work_id: W55058445
    a99eb94766324f9eb88ab0f6e7acd0b0:
      title: 'CII_Chapter VIII: Karmakārakaparīkṣā'
      base_file: 'CII_Chapter VIII: Karmakārakaparīkṣā.txt'
      work_id: W71D0A4AC
    59b60551e05947c086a743aa4814f46e:
      title: 'CII_Chapter X: Agnīndhanaparīkṣā'
      base_file: 'CII_Chapter X: Agnīndhanaparīkṣā.txt'
      work_id: W2C562FFE
    6a84a0a9b8cb4df1a33b244c0ea9c1ce:
      title: 'CIV_Chapter XIX: Kālaparīkṣā'
      base_file: 'CIV_Chapter XIX: Kālaparīkṣā.txt'
      work_id: WA05210A6
    223d30b86fe741448bd234c312638a64:
      title: 'CIV_Chapter XVI: Bandhanamokṣaparīkṣā'
      base_file: 'CIV_Chapter XVI: Bandhanamokṣaparīkṣā.txt'
      work_id: W94E6EC3E
    7e30e9d52d1645c68c3a92c3c7944434:
      title: 'CIV_Chapter XVII: Karmaphalaparīkṣā'
      base_file: 'CIV_Chapter XVII: Karmaphalaparīkṣā.txt'
      work_id: WF95F82F5
    bbfb733510274e6b9abf2040962fd852:
      title: 'CIV_Chapter XVIII: Ātmaparīkṣā'
      base_file: 'CIV_Chapter XVIII: Ātmaparīkṣā.txt'
      work_id: W6F56F7F5
    d7769283a7e54e6a83ccf311eed25ec2:
      title: 'CIV_Chapter XX: Sāmagrīparīkṣā'
      base_file: 'CIV_Chapter XX: Sāmagrīparīkṣā.txt'
      work_id: W9B493F31
    30f6a9c51b394c93a571ca41ac9ab7c8:
      title: 'CI_Chapter I: Pratyayaparīkṣā'
      base_file: 'CI_Chapter I: Pratyayaparīkṣā.txt'
      work_id: W4E77BE6D
    54d9245d413e422a96db5e148bc8282f:
      title: 'CI_Chapter II: Gatāgataparīkṣaṇa'
      base_file: 'CI_Chapter II: Gatāgataparīkṣaṇa.txt'
      work_id: W9D588B32
    be4ff7f3753c4cf89bff807b8277d1bb:
      title: 'CI_Chapter III: Cakṣurādīndriyaparīkṣā'
      base_file: 'CI_Chapter III: Cakṣurādīndriyaparīkṣā.txt'
      work_id: W9D354B9B
    1229fe4f43c042c18b7a938a68077bd3:
      title: 'CI_Chapter IV: Skandhaparīkṣā'
      base_file: 'CI_Chapter IV: Skandhaparīkṣā.txt'
      work_id: WFC0E7F11
    f86f2280c9d74cd4bce671b512c69349:
      title: 'CI_Chapter V: Dhātuparīkṣā'
      base_file: 'CI_Chapter V: Dhātuparīkṣā.txt'
      work_id: WD321A311
    ea9b056680c5485aa34fc2d637cfbaa8:
      title: 'CVI_Chapter XXVI: Dvādaśāṅgaparīkṣā'
      base_file: 'CVI_Chapter XXVI: Dvādaśāṅgaparīkṣā.txt'
      work_id: W2867C9BA
    1516f52018084e6482b51555971f41a6:
      title: 'CVI_Chapter XXVII: Dr̥ṣṭiparīkṣā'
      base_file: 'CVI_Chapter XXVII: Dr̥ṣṭiparīkṣā.txt'
      work_id: W92525862
    1b7c9ae8e4d940ba85612589315b9529:
      title: 'CV_Chapter XXI: Saṃbhavavibhavaparīkṣā'
      base_file: 'CV_Chapter XXI: Saṃbhavavibhavaparīkṣā.txt'
      work_id: WB77C1BC9
    64afbee237a3418b8a2677ec163aad0b:
      title: 'CV_Chapter XXII: Tathāgataparīkṣā'
      base_file: 'CV_Chapter XXII: Tathāgataparīkṣā.txt'
      work_id: WB726AD74
    39150724369e4b2b8dde503b1ad47c80:
      title: 'CV_Chapter XXIII: Viparyāsaparīkṣā'
      base_file: 'CV_Chapter XXIII: Viparyāsaparīkṣā.txt'
      work_id: WAA9A88EC
    4ab60762ab594171b49cd0934393b16c:
      title: 'CV_Chapter XXIV: Āryasatyaparīkṣā'
      base_file: 'CV_Chapter XXIV: Āryasatyaparīkṣā.txt'
      work_id: WCBDC8F38
    9e5df775bc8242308fc3d4aee305b162:
      title: 'CV_Chapter XXV: nirvāṇaparīkṣā'
      base_file: 'CV_Chapter XXV: nirvāṇaparīkṣā.txt'
      work_id: WE242A38C
    541d0968786c44ffaa5787553f8ac9ba:
      title: Colophon
      base_file: Colophon.txt
      work_id: W5BCE955E
    5406cdc0074f418f8e73478e9d76038d:
      title: Preface
      base_file: Preface.txt
      work_id: W6BD09F77
    b462e639ca024dd2b6004e18375fae87:
      title: Title
      base_file: Title.txt
      work_id: WDC4C8816
  chapter_to_tile:
    CI: Chapters I-V
    CII: Chapters VI-X
    CIII: Chapters XI-XV
    CIV: Chapters XVI-XX
    CV: Chapters XXI-XXV
    CVI: Chapters XXVI-XXVII
created_at: '2022-03-01T23:09:17.808628'
last_modified_at: '2022-03-01T23:09:17.808636'
